name: MarcoPlatino
theme: minima
remote_theme: jekyll/minima  # Use the remote theme from the GitHub repository
plugins:
  - jekyll-remote-theme # Activate the remote theme plugin
minima:
  skin: solarized-dark
